import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistGeist = Geist({subsets:['latin'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-geist'});

const geistMonoGeistMono = Geist_Mono({subsets:['latin'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-geist-mono'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(geistGeist.variable, geistMonoGeistMono.variable)}>
      <body
        className={`${geistGeist.variable} ${geistMonoGeistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
